import SwiftUI
import SwiftData

/// "Luna says" card on the Home tab — a moment of personality from the dog.
/// Replaces the old single-line `DailyDogVoiceRow`. The line is generated by
/// `LLMService.dogChatLine(for:)`, which caches per (dog × local-day × time
/// slot) so we burn at most three LLM calls per dog per day even if the user
/// opens the app dozens of times.
///
/// Time-of-day slots:
///   - morning (5-12)   → fact about the breed, age, or species
///   - afternoon (12-17) → playful question for the user
///   - evening (17-22)  → wry one-liner / joke
///   - night (22-5)     → reuses the evening slot's cache
///
/// On LLM miss we fall back to a templated line keyed off breed + slot, so
/// the card never disappears or shows a blank state.
struct DogChatCard: View {
    let dog: Dog

    @State private var line: String = ""
    @State private var slotLabel: String = ""

    var body: some View {
        VStack(alignment: .leading, spacing: Space.sm) {
            HStack(spacing: 6) {
                Image(systemName: "quote.opening")
                    .font(.system(size: 14, weight: .semibold))
                    .foregroundStyle(Color.brandPrimary)
                Text("\(dog.name.uppercased()) SAYS")
                    .font(.caption.weight(.semibold))
                    .tracking(0.5)
                    .foregroundStyle(Color.brandTextSecondary)
                Spacer()
                if !slotLabel.isEmpty {
                    Text(slotLabel.uppercased())
                        .font(.caption2.weight(.semibold))
                        .tracking(0.5)
                        .foregroundStyle(Color.brandTextTertiary)
                }
            }
            Text(displayedLine)
                .font(.titleSmall)
                .italic()
                .foregroundStyle(Color.brandTextPrimary)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(Space.md)
        .background(Color.brandPrimaryTint)
        .clipShape(RoundedRectangle(cornerRadius: Radius.lg))
        .accessibilityElement(children: .combine)
        .accessibilityLabel("\(dog.name) says: \(displayedLine)")
        .task(id: dog.persistentModelID) {
            await refresh()
        }
    }

    /// Templated fallback before the LLM lands (or on LLM miss). Keyed off
    /// the current slot so the fallback at least matches the time-of-day flavor.
    private var displayedLine: String {
        if !line.isEmpty { return line }
        return Self.fallback(for: LLMService.DogChatSlot.current(now: .now, calendar: .current), dog: dog)
    }

    private func refresh() async {
        let slot = LLMService.DogChatSlot.current(now: .now, calendar: .current)
        await MainActor.run { slotLabel = slotDisplay(for: slot) }
        if let llmLine = await LLMService.dogChatLine(for: dog) {
            await MainActor.run {
                withAnimation(.brandDefault) {
                    self.line = llmLine
                }
            }
        }
    }

    private func slotDisplay(for slot: LLMService.DogChatSlot) -> String {
        switch slot {
        case .morning: return "morning"
        case .afternoon: return "afternoon"
        case .evening: return "evening"
        }
    }

    /// Static fallback library — used when the LLM is offline, throttled, or
    /// hasn't responded yet. Keyed to slot so the time-of-day flavour is
    /// right; rotated deterministically by (dog × day × slot) so the user
    /// sees variety across days without it feeling random within a session.
    /// Pulls from a wider bank than the LLM-disabled v1 of this card to
    /// guarantee character even on cold start.
    static func fallback(
        for slot: LLMService.DogChatSlot,
        dog: Dog,
        now: Date = .now,
        calendar: Calendar = .current
    ) -> String {
        let name = dog.name
        let pool: [String] = lines(for: slot, name: name, breed: dog.breedPrimary)
        let dayKey = Self.dayKey(now, calendar: calendar)
        var hasher = Hasher()
        hasher.combine(dog.persistentModelID.hashValue)
        hasher.combine(dayKey)
        hasher.combine(slot.rawValue)
        hasher.combine("fallback") // distinct from the LLM category-pick hash
        let value = abs(hasher.finalize())
        return pool[value % pool.count]
    }

    private static func dayKey(_ date: Date, calendar: Calendar) -> String {
        let comps = calendar.dateComponents([.year, .month, .day], from: date)
        return "\(comps.year ?? 0)-\(comps.month ?? 0)-\(comps.day ?? 0)"
    }

    /// The fallback bank. Lines stay in-character: dry, slightly dramatic,
    /// specific where they can be. Some lean on breed if we can identify a
    /// flavour from the breed string; others are universal.
    private static func lines(for slot: LLMService.DogChatSlot, name: String, breed: String) -> [String] {
        let breedFlavour = breedAside(for: breed)
        switch slot {
        case .morning:
            return [
                "Morning. The garden has been audited. Three new smells.",
                "Briefing: birds at six o'clock, postman due at nine.",
                "I dreamed about cheese. Then I dreamed about more cheese.",
                "Up. Stretched. Thought about breakfast for forty minutes.",
                "\(breedFlavour) Currently waiting for a sock to fall.",
                "The day is long, the lead is short. Let's address that.",
                "I checked: the squirrels still exist. Worrying.",
            ]
        case .afternoon:
            return [
                "Park or river? You pick. I'll lead.",
                "Phase one of today's plan: look pitiful near the kitchen.",
                "Hypothesis: the postman is suspicious. Evidence: he leaves.",
                "Guess what's behind the bins. Go on.",
                "If we leave now, we beat the small dog with the loud opinions.",
                "I have done nothing for two hours. It feels structured.",
                "\(breedFlavour) Open to lunchtime suggestions.",
            ]
        case .evening:
            return [
                "Long day. Going to lie down dramatically.",
                "Three walks would have been better, but I respect your choices.",
                "I've decided the rug is mine now. We'll talk about it tomorrow.",
                "Settling in. The sofa knows what it did.",
                "If anyone calls, tell them I'm asleep. I'm not, but tell them.",
                "\(breedFlavour) Currently fighting the urge to bark at nothing.",
                "Tonight's plot: get on the bed before you notice.",
            ]
        }
    }

    /// Breed-flavoured aside used inside the bigger fallback lines. Matches
    /// the dog's breed family loosely so a sighthound line doesn't show up
    /// for a French Bulldog. Defaults to a neutral one-liner.
    private static func breedAside(for breed: String) -> String {
        let lower = breed.lowercased()
        if lower.contains("beagle") || lower.contains("hound") {
            return "Bred to follow my nose."
        }
        if lower.contains("terrier") {
            return "Bred to dig things up. Working on the carpet."
        }
        if lower.contains("retriever") || lower.contains("labrador") {
            return "Bred to fetch. Currently fetching nothing."
        }
        if lower.contains("collie") || lower.contains("shepherd") || lower.contains("kelpie") {
            return "Bred to herd. Counting things in the kitchen."
        }
        if lower.contains("spaniel") {
            return "Bred to flush birds. Currently flushing crumbs."
        }
        if lower.contains("bulldog") || lower.contains("pug") || lower.contains("frenchie") {
            return "Bred to be a chair, mostly."
        }
        if lower.contains("husky") || lower.contains("malamute") {
            return "Bred to pull a sled. Pulling at the lead instead."
        }
        if lower.contains("dachshund") || lower.contains("sausage") {
            return "Long. Low. Determined."
        }
        return "Doing the job, more or less."
    }
}
