import SwiftUI
import SwiftData

/// "Luna says" card on the Home tab — a moment of personality from the dog.
/// Replaces the old single-line `DailyDogVoiceRow`. The line is generated by
/// `LLMService.dogChatLine(for:)`, which caches per (dog × local-day × time
/// slot) so we burn at most three LLM calls per dog per day even if the user
/// opens the app dozens of times.
///
/// Time-of-day slots:
///   - morning (5-12)   → fact about the breed, age, or species
///   - afternoon (12-17) → playful question for the user
///   - evening (17-22)  → wry one-liner / joke
///   - night (22-5)     → reuses the evening slot's cache
///
/// On LLM miss we fall back to a templated line keyed off breed + slot, so
/// the card never disappears or shows a blank state.
struct DogChatCard: View {
    let dog: Dog

    @State private var line: String = ""
    @State private var slotLabel: String = ""

    var body: some View {
        VStack(alignment: .leading, spacing: Space.sm) {
            HStack(spacing: 6) {
                Image(systemName: "quote.opening")
                    .font(.system(size: 14, weight: .semibold))
                    .foregroundStyle(Color.brandPrimary)
                Text("\(dog.name.uppercased()) SAYS")
                    .font(.caption.weight(.semibold))
                    .tracking(0.5)
                    .foregroundStyle(Color.brandTextSecondary)
                Spacer()
                if !slotLabel.isEmpty {
                    Text(slotLabel.uppercased())
                        .font(.caption2.weight(.semibold))
                        .tracking(0.5)
                        .foregroundStyle(Color.brandTextTertiary)
                }
            }
            Text(displayedLine)
                .font(.titleSmall)
                .italic()
                .foregroundStyle(Color.brandTextPrimary)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(Space.md)
        .background(Color.brandPrimaryTint)
        .clipShape(RoundedRectangle(cornerRadius: Radius.lg))
        .accessibilityElement(children: .combine)
        .accessibilityLabel("\(dog.name) says: \(displayedLine)")
        .task(id: dog.persistentModelID) {
            await refresh()
        }
    }

    /// Templated fallback before the LLM lands (or on LLM miss). Keyed off
    /// the current slot so the fallback at least matches the time-of-day flavor.
    private var displayedLine: String {
        if !line.isEmpty { return line }
        return Self.fallback(for: LLMService.DogChatSlot.current(now: .now, calendar: .current), dog: dog)
    }

    private func refresh() async {
        let slot = LLMService.DogChatSlot.current(now: .now, calendar: .current)
        await MainActor.run { slotLabel = slotDisplay(for: slot) }
        if let llmLine = await LLMService.dogChatLine(for: dog) {
            await MainActor.run {
                withAnimation(.brandDefault) {
                    self.line = llmLine
                }
            }
        }
    }

    private func slotDisplay(for slot: LLMService.DogChatSlot) -> String {
        switch slot {
        case .morning: return "morning"
        case .afternoon: return "afternoon"
        case .evening: return "evening"
        }
    }

    /// Tiny static fallback set so the card always has something to say even
    /// if the proxy is offline. Keyed to slot so the time-of-day flavour
    /// matches the user's expectation; uses `dog.name` so it still feels
    /// personalised.
    static func fallback(for slot: LLMService.DogChatSlot, dog: Dog) -> String {
        let name = dog.name
        switch slot {
        case .morning:
            return "Morning. \(name) reporting for duty."
        case .afternoon:
            return "What's the plan, then."
        case .evening:
            return "Long day. Going to lie down dramatically."
        }
    }
}
